# Generated by Django 4.1.7 on 2023-04-23 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_trade_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='price',
        ),
    ]
